apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ueni7am3r-nodejs 
  janus-idp.io/tekton: ueni7am3r-nodejs
  backstage.io/kubernetes-id: ueni7am3r-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ueni7am3r-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml